version: "3.9"
services:
  producer:
    build:
      context: .
      dockerfile: ./produce/Dockerfile
    depends_on:
      - "proxy"
    command: ["-broker", "proxy:8080"]
    stdin_open: true
  consumer:
    build:
      context: .
      dockerfile: ./consume/Dockerfile
    depends_on:
      - "proxy"
    command: ["-broker", "proxy:8080"]
  proxy:
    image: "ghcr.io/maxwellpeterson/kafka-websocket-proxy:main"
    depends_on:
      - "broker"
    command: ["-broker", "broker:8787"]
  broker:
    image: "ghcr.io/maxwellpeterson/kafka-worker:main"
    volumes:
      - .dev.vars:/app/.dev.vars
